
name: Rx

on: 
  push:
    branches: [master]
    pull_request: 
      branches: [master]


env:
  CARGO_TERM_COLOR: always


jobs:
  verify: 
    name: verify the project
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
         os: [ubuntu-latest, macOS-latest, windows-latest]

      steps: 
        - name: Checkout
          uses: actions/checkout/@v2
        
        - name: Build project
          shell: bash 
          run: cargo build --verbose

        - name: Run tests
          shell: bash
          run: cargo test --verbose